name: simple_dart_headed_panel
description: Headed Panel Component
version: 0.0.2
repository: https://github.com/simple-dart/headed_panel
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_label: ^0.0.1
  simple_dart_ui_core: ^0.0.3
